spring.application.name=event_fundraising_service

spring.data.mongodb.uri=mongodb://event-fundraising-mongo-db:27017/event-fundraising-collection

#rabbit
spring.rabbitmq.host=${RABBIT_HOST}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
#queues
app.rabbitmq.user-events-exchange=user.events.exchange
app.rabbitmq.contribution-events-exchange=contribution.events.exchange
app.rabbitmq.user-events-queue=user.events.queue
app.rabbitmq.contribution-events-queue=contribution.events.queue

#jwt
jwt.secret.b64=${JWT_SECRET_B64}
jwt.issuer=${JWT_ISSUER}
jwt.expiration-ms=${JWT_EXPIRATION_MS:36000000}

#logs
management.endpoints.web.exposure.include=health,info,mappings
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n
