spring.application.name=event_campaign_service

spring.data.mongodb.uri=mongodb://event-campaign-mongo-db:27017/event-campaign-collection
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n

spring.rabbitmq.host=${RABBIT_HOST}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

jwt.secret.b64=${JWT_SECRET_B64}
jwt.issuer=${JWT_ISSUER}
jwt.expiration-ms=${JWT_EXPIRATION_MS:36000000}

management.endpoints.web.exposure.include=health,info,mappings
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE